// Arquivo: actions.cpp
#include "token.h"
#include "actions.h"

ActionsMap initActions()
{
    return {
        // {0, {gtoken_program, {token_tome, token_id, token_chv_esq, gtoken_cmd_init, token_chv_dir}}},
        {0, [](std::vector<t_token> tokens) -> t_token{ return tokens[0]; }},
        // {1, {gtoken_cmd_init, {token_ingredients, token_chv_esq, gtoken_declare_sq, token_chv_dir, gtoken_cmd_sq}}},
        // {2, {gtoken_cmd_init, {gtoken_cmd_sq}}},
        // {3, {gtoken_declare_sq, {gtoken_type, token_id, token_endline, gtoken_declare_sq}}},
        // {4, {gtoken_declare_sq, {gtoken_type, token_id, token_atr, gtoken_value, token_endline, gtoken_declare_sq}}},
        // {5, {gtoken_cmd_sq, {gtoken_operation, token_endline, gtoken_cmd_sq}}},
        // {6, {gtoken_operation, {gtoken_assign_sq}}},
        // {7, {gtoken_operation, {gtoken_control}}},
        // {8, {gtoken_operation, {gtoken_for_sq}}},
        // {9, {gtoken_operation, {gtoken_summon_sq}}},
        // {10, {gtoken_operation, {gtoken_echo_sq}}},
        // {11, {gtoken_assign_sq, {token_id, token_atr, gtoken_logic}}},
        // {12, {gtoken_for_sq, {token_for, token_par_esq, gtoken_assign_sq, token_endline, gtoken_logic, token_endline, token_int, token_par_dir, gtoken_block}}},
        // {13, {gtoken_summon_sq, {token_summon, token_par_esq, gtoken_id, token_par_dir}}},
        // {14, {gtoken_echo_sq, {token_echo, token_par_esq, token_string, token_par_dir}}},
        // {15, {gtoken_echo_sq, {token_echo, token_par_esq, gtoken_id, token_par_dir}}},
        // {16, {gtoken_control, {gtoken_control_struc, gtoken_expression, gtoken_block}}},
        // {17, {gtoken_control_struc, {token_if}}},
        // {18, {gtoken_control_struc, {token_while}}},
        // {19, {gtoken_block, {token_chv_esq, gtoken_cmd_sq, token_chv_dir}}},
        // {20, {gtoken_expression, {token_par_esq, gtoken_logic, token_par_dir}}},
        // {21, {gtoken_logic, {gtoken_logic, gtoken_op_logic, gtoken_bool_op}}},
        // {22, {gtoken_logic, {gtoken_bool_op}}},
        // {23, {gtoken_bool_op, {gtoken_relacional}}},
        // {24, {gtoken_bool_op, {token_not, gtoken_relacional}}},
        // {25, {gtoken_relacional, {gtoken_relacional, gtoken_op_rel, gtoken_relacional_op}}},
        // {26, {gtoken_relacional, {gtoken_relacional_op}}},
        // {27, {gtoken_relacional_op, {gtoken_expr}}},
        // {28, {gtoken_relacional_op, {token_par_esq, gtoken_relacional, token_par_dir}}},
        // {29, {gtoken_expr, {gtoken_expr, gtoken_op_art_pr, gtoken_term}}},
        // {30, {gtoken_expr, {gtoken_term}}},
        // {31, {gtoken_term, {gtoken_term, gtoken_op_art_sc, gtoken_factor}}},
        // {32, {gtoken_term, {gtoken_factor}}},
        // {33, {gtoken_factor, {token_par_esq, gtoken_expr, token_par_dir}}},
        // {34, {gtoken_factor, {gtoken_value}}},
        // {35, {gtoken_factor, {gtoken_id}}},
        // {36, {gtoken_id, {token_id}}}, // gtoken_id.value = token_id.data
        // {37, {gtoken_id, {token_id, token_col_esq, token_int, token_col_dir}}},
        // {38, {gtoken_op_logic, {token_and}}},
        // {39, {gtoken_op_logic, {token_or}}},
        // {40, {gtoken_op_rel, {token_gr}}},
        // {41, {gtoken_op_rel, {token_le}}},
        // {42, {gtoken_op_rel, {token_eq}}},
        // {43, {gtoken_op_art_pr, {token_add}}},
        // {44, {gtoken_op_art_pr, {token_sub}}},
        // {45, {gtoken_op_art_sc, {token_mul}}},
        // {46, {gtoken_op_art_sc, {token_div}}},
        // {47, {gtoken_value, {token_int}}},
        // {48, {gtoken_value, {token_float}}},
        // {49, {gtoken_value, {token_string}}},
        // {50, {gtoken_type, {token_type_int}}},
        // {51, {gtoken_type, {token_type_int, token_col_esq, token_int, token_col_dir}}},
        // {52, {gtoken_type, {token_type_float}}},
        // {53, {gtoken_type, {token_type_float, token_col_esq, token_int, token_col_dir}}},
        // {54, {gtoken_type, {token_type_string}}},
        // {55, {gtoken_declare_sq, {gtoken_type, token_id, token_endline}}},
        // {56, {gtoken_declare_sq, {gtoken_type, token_id, token_atr, gtoken_value, token_endline}}},
        // {57, {gtoken_id, {token_id, token_col_esq, token_id, token_col_dir}}},
        // {58, {gtoken_cmd_sq, {gtoken_operation, token_endline}}},
        // {59, {gtoken_cmd_sq, {}}},
        // {60, {gtoken_block, {token_chv_esq, token_chv_dir}}},
        // {61, {gtoken_cmd_init, {token_ingredients, token_chv_esq, gtoken_declare_sq, token_chv_dir}}},
    };
}
